version: "3.8"
services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - order-service
    networks:
      - my-network

  user-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    volumes:
      - user-db-data:/var/lib/postgresql/data
    networks:
      - my-network

  order-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_db
    volumes:
      - order-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"  # External port 5433 mapped to internal 5432 for order-db
    networks:
      - my-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8083:80"
    depends_on:
      - user-db
      - order-db
    networks:
      - my-network

  user-service:
    build: ./user-service
    environment:
      DB_HOST: user-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: user_db
    depends_on:
      - user-db
    ports:
      - "8081:8080"
    networks:
      - my-network

  order-service:
    build: ./order-service
    environment:
      DB_HOST: order-db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: password
      DB_NAME: order_db
    depends_on:
      - order-db
    ports:
      - "8082:8080"
    networks:
      - my-network

networks:
  my-network:

volumes:
  user-db-data:
  order-db-data:
